### ISSUE TITLE
了解BFC特性，轻松实现自适应布局

### ISSUE THREAD

**Issue by maicFir** [maicFir/lessonNote#42]
> BFC(`Block Formatting Context`)俗称块级格式上下文,初次看到这词似乎有点不是很理解，通俗解释就是一个独立区域决定了内部元素的排放，以及内部元素与外部元素的相互作用关系

正文开始...

### BFC 是什么

俗称块级格式上下文，一块独立的区域决定了内部元素的位置排列，以及内部元素与外部元素的作用关系

### BFC 特点

我们先了解下`BFC`有什么特点

1、垂直方向，`相邻BFC`的块级元素会产生外边距合并

2、BFC 包含浮动元素,浮动会触发新的 BFC 产生

3、已经确定的 BFC 区域不会与相邻 BFC 的浮动元素边距发生重合

针对以上几点我来具体深究一下 BFC 的特性到底有何区别，在什么样的场景下会比较触发`BFC`

新建一个`index.html`测试

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BFC</title>
    <style>
      * {
        padding: 0;
        margin: 0;
      }
      .wrap-box {
        width: 300px;
      }
      .inner-box {
        width: 100px;
        height: 50px;
      }
      .inner-box:nth-of-type(2n + 1) {
        background-color: red;
      }
    </style>
  </head>
  <body>
    <div class="wrap-box">
      <div class="inner-box">1</div>
      <div class="inner-box">2</div>
      <div class="inner-box">3</div>
    </div>
  </body>
</html>
```

不出意外在`wrap-box`这个 BFC 中，内部元素垂直单行排列
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/92e570b31b8348a8b222be909e3869d9~tplv-k3u1fbpfcp-zoom-1.image)
这说明块级格式上下文，在`wrap-box`这个元素决定了内部的元素排放，因为子元素始终是被包裹起来的,因为是块级元素，所以单行排列。

接下来我们将子元素添加外边距`margin:10px 0`;

```css
* {
  padding: 0;
  margin: 0;
}
.wrap-box {
  width: 300px;
}
.inner-box {
  width: 100px;
  height: 50px;
  margin: 10px 0;
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/0ac2aa4ab4f242d99acc4bf5e2240f36~tplv-k3u1fbpfcp-zoom-1.image)
另外我们看下`wrap-box`的盒子模型
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/fc133cf55045473fb5f3abfb31840bab~tplv-k3u1fbpfcp-zoom-1.image)
在子元素`inner-box`我们加了外边距`margin`,我们从已知的`BFC`特点知道相邻的`BFC`外边距会合并。

因为被包裹的`inner-box`是三个块级元素，在`wrap-box`内部来说，这三个内部`div`形成独立的`BFC`，所以相邻的`1-2，2-3`的外边距就合并了。

现在我有个需求，我不想让他们合并，我要破坏内部的三个 BFC 结构怎么办？

因此我需要将第二个`inner-box`改造成一个新的 BFC 结构

```html
<div class="wrap-box">
  <div class="inner-box">1</div>
  <div class="inner-box-2">
    <div class="inner-box">2</div>
  </div>
  <div class="inner-box">3</div>
</div>
```

注意我在第二个元素多加了一层结构
因此结构变成下面这样，主要看第三个图，我用虚线标出了表明第二元素已经被加了一层结构，貌似外边距还是会合并，这是为啥？
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/54d1ffc35c0f4fc0a2971d758416f436~tplv-k3u1fbpfcp-zoom-1.image)
从新的结构我们可以知晓，`相邻块级元素的BFC`会使边距发生合并，以前的内部的 BFC 是`123`,现在新的 BFC 是`143`,`2`已经被`4`包裹独立出来了,在 2 内部的`margin`会作用到父级，从而作用到父级相邻的 BFC 结构。

我们继续在`4`上添加一个`margin:10px 0`,神奇的事情发生了，居然还是一样边距被合并了，具体看下代码

```css
.wrap-box {
  width: 300px;
}
.inner-box {
  width: 100px;
  height: 50px;
  margin: 10px 0;
  overflow: hidden;
}
.inner-box:nth-of-type(2n + 1) {
  background-color: red;
}
.inner-box-2 {
  margin: 10px 0;
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/69db6c38e33348b784d551e48be6de78~tplv-k3u1fbpfcp-zoom-1.image)
你会发现居然在`2`的外层加了`magrin`,居然不会影响整个盒模型的高度。

因此你再细品那句话`相邻块级格式上下文的上下边距会产生重叠`，于是你恍然大悟，`143`是三个 BFC 结构，所以 4 设置`margin`自然就被重合了。

但是我要破坏这种相邻 BFC 结构，因此触发 BFC 结构的机会来了。我给`inner-box-2`加个样式，用`overflow:hidden`触发生成一个新的 BFC;

现在就变成了这样了
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/cd7231e775c24f7d8f6f2ac87407a747~tplv-k3u1fbpfcp-zoom-1.image)
没错，盒子模型高度变成了`190`了,中间的`4`外边距没有合并了。
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/d614a34717d84f61a75fea965017f23c~tplv-k3u1fbpfcp-zoom-1.image)

由于在`4`不是虽然不是根元素，但是身上加了`overflow:hidden`触发`4`形成一个新的 BFC,那么触发 BFC 还有其他什么方式吗？

我们了解到除了`overflow:hidden`,还有以下几种方式
` overflow: auto;display: flex; display: table;display: -webkit-box; float: left;`

```css
.inner-box-2 {
  margin: 10px 0;
  overflow: hidden;
  /* overflow: auto; */
  /* display: flex; */
  /* display: table; */
  /* display: -webkit-box; */
  /* float: left; */
}
```

### 已经确定的 BFC 不会与相邻浮动的 BFC 边距发生重合

当我们把`inner-box-2`设置为浮动后，边距就不会合并了。这也证实了相邻 BFC 与已经设置的浮动元素边距并不会合并，但`inner-box-2`与`inner-box-1`始终在一个大的`BFC`包裹着，而每一个自身元素又形成一个独立的`BFC`。
:::: code-group
::: code-group-item html
```html
<div class="wrap-box">
  <div class="inner-box inner-box-1">1</div>
  <div class="inner-box inner-box-2">2</div>
</div>
```
:::
::: code-group-item css
```css
 <style>
    *{
      padding: 0;
      margin: 0;
    }
    .wrap-box {
      width: 300px;
      border: 1px solid #111;
      overflow: hidden;
    }
    .inner-box {
      width: 100px;
      height: 50px;
      margin: 10px 0;
      overflow: hidden;
    }
    .inner-box-2 {
      float: left;
    }
    .inner-box:nth-of-type(2n+1) {
      background-color: red;
    }
    .inner-box:nth-of-type(2n) {
      background-color: yellow;
    }
  </style>
```
:::
::::
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/e314ada63ecb4f95932acbf5c492331d~tplv-k3u1fbpfcp-zoom-1.image)

### 探索 BFC 九宫格布局

我们知道相邻的 BFC 结构垂直方向外边距会合并,利用这点，我们实现九宫格布局
:::: code-group
::: code-group-item html
```html
<div class="wrap-box">
  <div class="inner-box">1</div>
  <div class="inner-box">2</div>
  <div class="inner-box">3</div>
  <div class="inner-box">4</div>
  <div class="inner-box">5</div>
  <div class="inner-box">6</div>
  <div class="inner-box">7</div>
  <div class="inner-box">8</div>
  <div class="inner-box">9</div>
</div>
```
:::
::: code-group-item css
```css
* {
  padding: 0;
  margin: 0;
}
.wrap-box {
  width: 300px;
  border: 1px solid #111;
  display: flex;
  flex-wrap: wrap;
}
.inner-box {
  width: 100px;
  height: 50px;
  margin: 10px 0;
  overflow: hidden;
  float: left;
}
.inner-box:nth-of-type(2n + 1) {
  background-color: red;
}
.inner-box:nth-of-type(2n) {
  background-color: yellow;
}
```
:::
::::
注意我们给所有的子元素加了浮动，那么此时会造成父元素高度坍塌，因此父级元素必须要加上`overflow:hidden`或者设置`display: inlie-block`或者`position: absolute`;这样才可以导致父级元素不坍塌。

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9d3eb69921974430b451ea5be0b76e7e~tplv-k3u1fbpfcp-zoom-1.image)

貌似`456`中间元素因为设置浮动破坏了`BFC`,所以我们需要给`456`设置特殊`margin`才行,于是乎你给 456 加一层 div,然后设置`margin: -10px 0`并且要设置`左浮动`
:::: code-group
::: code-group-item css
```css
.item-2 {
  float: left;
  margin: -10px 0;
}
```
:::
::: code-group-item html
```html
<div class="wrap-box">
  <div class="inner-box">1</div>
  <div class="inner-box">2</div>
  <div class="inner-box">3</div>
  <div class="item-2">
    <div class="inner-box">4</div>
    <div class="inner-box">5</div>
    <div class="inner-box">6</div>
  </div>
  <div class="inner-box">7</div>
  <div class="inner-box">8</div>
  <div class="inner-box">9</div>
</div>
```
:::
:::: 
OK 已经可以了
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/05ea6ffe5fc74ca7bdd122016d07cf12~tplv-k3u1fbpfcp-zoom-1.image)

此时我们这样改 dom 结构似乎有点不是很好，因为可能数据是从后端接口返回并不是写死的数据结构，因此我们再改下结构布局
:::: code-group
::: code-group-item html
```html
<div class="wrap-box">
  <div class="item">
    <div class="inner-box">1</div>
    <div class="inner-box">2</div>
    <div class="inner-box">3</div>
  </div>

  <div class="item">
    <div class="inner-box">4</div>
    <div class="inner-box">5</div>
    <div class="inner-box">6</div>
  </div>
  <div class="item">
    <div class="inner-box">7</div>
    <div class="inner-box">8</div>
    <div class="inner-box">9</div>
  </div>
</div>
```
::: 
::: code-group-item css
```css
* {
  padding: 0;
  margin: 0;
}
.wrap-box {
  width: 300px;
  border: 1px solid #111;
  overflow: hidden;
}
.inner-box {
  width: 100px;
  height: 50px;
  overflow: hidden;
  float: left;
}
.inner-box:nth-of-type(2n + 1) {
  background-color: red;
}
.inner-box:nth-of-type(2n) {
  background-color: yellow;
}
.item {
  margin: 10px 0;
  overflow: hidden;
}
```
::: 
::::
我们最初把`margin`作用在每个小元素下，现在我们利用`BFC`的特性，我们把`margin`作用在`item`上，因为三个`item`就是相邻垂直方向的 BFC 结构,边距会产生合并，也正是利用边距合并巧妙的解决了保持边距相等的问题。

具体可以看下效果
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/0e8bfc9be7db4be495236a9da107677d~tplv-k3u1fbpfcp-zoom-1.image)
由于不同的布局方式，因此写出来的页面拓展性是完全不一样，拓展性强的布局方式，对于后期的维护是相当有益。因此不推荐第一种方式改结构，然后特殊设置`456`的父边距，虽然效果能达到一致，但是后期维护性与拓展性不高。

### BFC 实现自适应布局

有时候左侧固定，右侧自适应这种页面结构时常会有，这种布局方案有哪些可以实现呢
:::: code-group
::: code-group-item html
```html
<h1>左边固定，右边自适应，右边随着左边的宽度而自适应</h1>
<div class="wrap-box">
  <div class="slide-left">left</div>
  <div class="main">main</div>
</div>
```
:::
::: code-group-item css
```css
* {
  padding: 0;
  margin: 0;
}
.wrap-box {
  width: 300px;
  border: 1px solid #111;
  overflow: hidden;
  resize: horizontal;
}
.slide-left {
  width: 100px;
  height: 100px;
  background-color: red;
}
.main {
  height: 100px;
  background-color: yellow;
}
```
:::
::::
此时发现页面不尽人意，肯定是下面这样的
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/0e494c47f6b94e948fe1f90b6425cc34~tplv-k3u1fbpfcp-zoom-1.image)
但是当我们给`slide-left`设置`float:left`后，我们会发现，此时`slide-left`的文档流被破坏，`main`会紧贴着`slide-left`排列

```css
.slide-left {
  width: 100px;
  height: 100px;
  background-color: red;
  resize: horizontal;
  float: left;
}
```

此时我们可以观察到`main`贴着`slide-left`,宽度就是父级的宽度
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/4fdec511b1554a58809001959ac6e839~tplv-k3u1fbpfcp-zoom-1.image)

但实际上`main`是需要剩下的宽度，他需要根据左侧的`slide-left`的宽度而自适应
因此你可以，让`main`成为一个独立 BFC，我们需要设置它`oveflow:hidden`就行
那么此时就会变成
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/ef3f22afcc334ab2b7721d3f2645226a~tplv-k3u1fbpfcp-zoom-1.image)
完整的 css 如下

```css
* {
  padding: 0;
  margin: 0;
}
.wrap-box {
  width: 300px;
  border: 1px solid #111;
  overflow: hidden;
  resize: horizontal;
}
.slide-left {
  width: 100px;
  height: 100px;
  background-color: red;
  float: left;
}
.main {
  height: 100px;
  background-color: yellow;
  overflow: hidden;
}
```

OK，现在就实现了右侧根据左侧宽度的大小自适应了。
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f2ae431910324b72a4edc48cf1aa1cab~tplv-k3u1fbpfcp-zoom-1.image)
更多关于 BFC 可以参考[MDN BFC](https://developer.mozilla.org/zh-CN/docs/Web/Guide/CSS/Block_formatting_context)

### 总结

- 了解什么是 BFC,BFC 简称块级格式上下文，它是一块独立的区域影响子元素的排列，相邻区域的 BFC 边距会产生重合

- 触发 BFC 条件有，`display: flex`、`display: inline-block`、`display:box`,`position:absolute`，或者`oveflow: hidden/auto`,`float:left`;

- 利用 BFC 实现九宫布局,本质利用相邻 BFC 外边距合并

- 左侧固定，右侧自适应布局

- 本文 [code example](https://github.com/maicFir/lessonNote/tree/master/html/02-BFC%E8%A7%A6%E5%8F%91)
