### ISSUE TITLE
flex弹性布局特性

### ISSUE THREAD

**Issue by maicFir** [maicFir/lessonNote#43]
`flex`在css布局中的是一个经常考察的知识点，虽然垂直居中问题已经问得快烂大街了，`flex`你虽然总是在用，但是总会有你不知道的盲点

本文是一篇关于`flex`布局相关的总结笔记，遇到比较刁钻的问题，当个知识拓展吧

在阅读本文之前，主要从以下几个方向去探讨`flex`

* flex布局又称为弹性布局，有何特征
* 关于flex的一些属性值
* `flex`如何实现垂直居中，如何实现一个对角排列布局

### flex特征
当我们对一个元素设置`flex`后，其子元素所有的`float`，`clean`、`vertical-align`属性都会失效，并且默认水平排列，并且宽度由自身元素内容决定。

### 影响主轴与交叉轴的属性——

* flex-direction

主要影响水平轴排列还是交叉轴排列
```css
.wrap-box {
  display: flex;
  // flex-direction: row; 默认从左往右
  flex-direction: row-revers; 顺序从右往左 
  flex-direction: column; 从上往下 
  flex-direction: column-reverse; 从下往上 
}
```
![](https://files.mdnice.com/user/24614/9900ade0-b2ea-479f-91ac-33aa8096f398.png)

* flex-wrap
主要影响水平轴元素是否换行，默认不换行`flex-wrap:nowrap`
```css
.wrap-box {
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap // 不换行
  // flex-wrap: wrap // 换行
  // flex-wrap: wrap-reverse 换行从下往上依次排列
}
```
* flex-flow

这个属性主要是`flex-direction`与`flex-wrap`的结合体
```css
.wrap-box {
  display: flex;
  flex-flow: row nowrap // 默认
}
```
* justify-content

主要影响`水平主轴`的排列顺序
```css
.wrap-box {
  display: flex;
  justify-content: flex-start // 左对齐排列
  // justify-content: center // 居中排列
  // justify-content: space-between // 两端对齐排列
  // justify-content: space-around // 间隔相等排列
  // justify-content: flex-end // 居右排列
}
```
* align-items

主要影响`交叉轴`垂直方向的排列
```css
.wrap-box {
  display: flex;
  align-items: flex-start; // 垂直方向从上往下排列
  // align-items: center 垂直方向居中排列
  // align-items: flex-end 垂直方向从下往上排列
  // align-items: stretch 会将子元素高度拉伸父元素一致(子元素未设置高度)
}
```
![](https://files.mdnice.com/user/24614/c6052c90-11ff-43e9-91eb-3832a0a1fbff.png)

### 关于item项目设置的属性

* order

决定子项目的顺序，`order`越小，越是排列在最前面

假设现在有个需求，css实现简单的跑马灯
:::: code-group
::: code-group-item html
```html
 <div class="wrap-box">
    <div class="item-1">1</div>
    <div class="item-2">2</div>
    <div class="item-3">3</div>
 </div>
```
:::
::: code-group-item css
```css
    @keyframes ani-1 {
        0% {
          order: 0;
        }
        50% {
          order: 1;
        }
        100% {
          order: 2;
        }
      }
      @keyframes ani-2 {
        0% {
          order: 1;
        }
        50% {
          order: 0;
        }
        100% {
          order: 1;
        }
      }
      @keyframes ani-3 {
        0% {
          order: 2;
        }
        50% {
          order: 2;
        }
        100% {
          order: 0;
        }
      }
  .wrap-box {
        width: 500px;
        height: 500px;
        overflow: hidden;
        display: flex;
        background-color: green;
        align-items: stretch;
      }
      .wrap-box .item-1,
      .wrap-box .item-2,
      .wrap-box .item-3 {
        width: 100px;
        height: 100px;
        background-color: red;
      }
      .wrap-box .item-1 {
        animation: ani-1 5s infinite;
        transition: order 1s ease;
      }
      .wrap-box .item-2 {
        animation: ani-2 5s infinite;
        transition: order 1s ease;
      }
      .wrap-box .item-3 {
        animation: ani-3 5s infinite;
        transition: order 1s ease;
      }
```
:::
::::
我们利用`css3`的动画帧，改变order的顺序，因此一个简易的css跑马灯就实现了，而且并没有改变`dom`的结构和顺序
![](https://files.mdnice.com/user/24614/7482ab3d-54ca-4cef-9ba0-abaee25830fc.gif)
* flex-basis

设置当前的item的固定宽度
```css
.wrap-box .item-3{
  flex-basis: 200px;
}
```
![](https://files.mdnice.com/user/24614/9eaa519b-0b5e-4d7a-b5fd-78b9bbb0a23a.png)

* flex-grow 

该属性是决定当前item的放大比例，默认是0
![](https://files.mdnice.com/user/24614/f5e57e6b-2119-454a-adf3-10d2770a28f5.png)

比如三个div,左右固定，中间内容自动撑开
![](https://files.mdnice.com/user/24614/7fa8ba48-772b-4369-bd04-adc0436e20f6.png)
* flex-shrink

当前item的缩小比例，默认的是0

* align-self

能控制单个`item`的排列，这个属性通常不是很常用，面试曾被这个css的属性布局问题给跪了

面试题大概是这样的，3个子div实现一个对角线布局,用`flex布局`,如果没想到这个`align-self`大概是实现不了

```css
.wrap-box {
    width: 500px;
    height: 500px;
    overflow: hidden;
    background-color: green;
    display: flex;
    justify-content: space-between;
}
 .wrap-box .item-1,
  .wrap-box .item-2,
  .wrap-box .item-3 {
    width: 100px;
    height: 100px;
    background-color: red;
}
.wrap-box .item-2 {
  align-self: center; // 垂直居中
}
.wrap-box .item-3 {
  align-self: flex-end; // 靠右
}
```
设置对应的`item`大概就是下面这样了
![](https://files.mdnice.com/user/24614/63a22224-d9ab-4aa7-8a57-3c89cad8fa78.png)
![](https://files.mdnice.com/user/24614/d16961a7-30f0-47e0-960e-4ec3133c9142.png)

### 关于flex:1的详解
通常我们设置`flex:1`，其实本质上是替代了以下几个参数
```css
.item3 {
  flex-grow:1;
  flex-shrink:1;
  flex-basis: 0%;
}
```
### 元素垂直居中

以下是一个基本的页面结构
:::: code-group
::: code-group-item html
```html
<div class="wrap">
    <div class="inner-box"></div>
</div>
```
:::
::: code-group-item css
```css
 .wrap {
        width: 100px;
        height: 100px;
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: red;
}
.wrap .inner-box {
  width: 50px;
  height: 50px;
  background: green;
}
```
:::
::::

![](https://files.mdnice.com/user/24614/c6d5aa95-3379-4dc2-a08e-694096de97dd.png)

### 总结

* 了解flex基本特征，影响水平轴与交叉轴的的属性主要受`flex-direction`这个属性的，默认水平`row`排列

* 当一个父级元素设置`flex`后，子级的`浮动`、`clear`,`vertain-align`属性都会失效，默认所有子级元素水平排列

* `flex`的一些特性，比如放大`flex-glow`、缩小`flex-shrink`,还有影响水平轴排列`just-content`，以及交叉轴排列`align-items`属性的设置

* align-self 这个属性可以单独控制当前元素的位置

* flex实现一个垂直居中

* 本文[code example](https://github.com/maicFir/lessonNote/tree/master/html/04-flex布局)
